visualize_potential: true

DWAPlannerROS:
#Robot Config Params
  acc_lim_theta: 0.6
  acc_lim_x: 0.5
  acc_lim_y: 0.0
  acc_limit_trans: 0.6
  max_vel_x: 0.5
  min_vel_x: -0.15 
  max_vel_y: 0.0
  min_vel_y: 0.0
  max_trans_vel: 0.5
  min_trans_vel: 0.07
  max_rot_vel: 0.4
  min_rot_vel: 0.00
#Forward Simulation Parameters
  sim_time: 3.0
  sim_granularity: 0.03
  vx_samples: 10
  vy_samples: 0
  vtheta_samples: 20
  penalize_negative_x: true
#Trajectory Scoring Parameters
  goal_distance_bias: 24.0
  path_distance_bias: 20.0
  occdist_scale: 1.9
  stop_time_buffer: 0.2
  forward_point_distance: 0.15
  scaling_speed: 0.25
  max_scaling_factor: 0.2
#Goal Tolerance Parameters
  xy_goal_tolerance: 0.15
  yaw_goal_tolerance: 0.07
#Oscillation Prevention Param
  oscillation_reset_dist: 0.05
#Global Plan PArameters
  prune_plan: false 

